spring:
    application:
        name: course
    datasource:
        username: sa
        password: password
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:testdb
    jpa:
        show-sql: true
