spring:
  docker:
    compose:
      enabled: true
      file: docker-compose.yml

  application:
    name: course

  jpa:
    show-sql: true
  flyway:
    locations:
        - classpath:db/migration
        - classpath:db/data
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8081/realms/dev
        registration:
          keycloak:
            authorization-grant-type: authorization_code
            client-id: course-student-portal
            client-secret: 8YGmXLTpllBsr3Ax67AkQ7EyhbzydIPf
            scope: openid

management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  info:
    env:
      enabled: true
    git:
        mode: simple

info:
  app:
    name: Course Student Portal
    description: Course Student Portal
    author:
      name: Heiko Bensch
    java:
      version: ${java.version}
