spring:
  h2:
    console:
      enabled: false
  docker:
    compose:
      enabled: false
  datasource:
    url: ${DB_URL}
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI}
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID}
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            scope: openid
management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  info:
    env:
      enabled: true
    git:
      mode: simple

info:
  app:
    name: Course Student Portal
    description: Course Student Portal
    author:
      name: Heiko Bensch
    java:
      version: ${java.version}
