spring:
  docker:
    compose:
      enabled: true
      file: docker-compose.yml

  application:
    name: course

  jpa:
    show-sql: true
  flyway:
    locations:
        - classpath:db/migration
        - classpath:db/data

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8081/realms/dev
        registration:
          keycloak:
            authorization-grant-type: authorization_code
            client-id: course-student-portal
            client-secret: 8YGmXLTpllBsr3Ax67AkQ7EyhbzydIPf
            scope: openid
