name: Clean Workflow Runs

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  clean-runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: dmvict/clean-workflow-runs@v1.0.0
        with:
          save_min_runs_number: 20
          save_period: 30
          token: ${{ secrets.GITHUB_TOKEN }}

