name: Publish package to GitHub Packages

on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      checks: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      #      - name: Publish JAR
      #        run: ./gradlew publish -Prelease.useLastTag=true
      #        env:
      #          USERNAME: ${{ secrets.USERNAME }}
      #          TOKEN: ${{ secrets.TOKEN }}

      - name: Publish Docker
        run: |
          echo ./gradlew -Prelease.useLastTag=true -Djib.to.auth.username="${{ github.actor }}" -Djib.to.auth.password="$GH_TOKEN" jib -x check
          ./gradlew -Prelease.useLastTag=true -Djib.to.auth.username="${{ github.actor }}" -Djib.to.auth.password="$GH_TOKEN" jib -x check --stacktrace --build-cache
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
